name: tts
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3 
  google_mlkit_text_recognition: ^0.5.0
  image_picker: ^0.8.7+1
  google_ml_kit: ^0.13.0
  image_cropper: ^3.0.2
  cupertino_icons: ^1.0.2
  google_mlkit_translation: ^0.5.0
  image: ^4.0.15
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

